### ISSUE TITLE
Deleting existing specification fails

### ISSUE THREAD

**Issue by MPParsley** [graphlit/graphlit-samples#4] opened 2024-05-30 08:51 UTC
The following error occurs when changing the json schema in the Extract_JSON step on https://graphlit-samples-extract-pdf-json.streamlit.app/.

```
graphlit_api.exceptions.GraphQLClientGraphQLMultiError: This app has encountered an error. The original error message is redacted to prevent data leaks. Full error details have been recorded in the logs (if you're on Streamlit Cloud, click on 'Manage app' in the lower right of your app).
Traceback:
File "/home/adminuser/venv/lib/python3.11/site-packages/streamlit/runtime/scriptrunner/script_runner.py", line 584, in _run_script
    exec(code, module.__dict__)
File "/mount/src/graphlit-samples/python/streamlit-multipage-extract-pdf-json/pages/3_Extract_JSON.py", line 36, in <module>
    helpers.run_async_task(extract.handle_extract)
File "/mount/src/graphlit-samples/python/streamlit-multipage-extract-pdf-json/other/helpers.py", line 29, in run_async_task
    return loop.run_until_complete(async_func(*args))
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
File "/usr/local/lib/python3.11/asyncio/base_events.py", line 654, in run_until_complete
    return future.result()
           ^^^^^^^^^^^^^^^
File "/mount/src/graphlit-samples/python/streamlit-multipage-extract-pdf-json/components/extract.py", line 9, in handle_extract
    await client.delete_specification()
File "/mount/src/graphlit-samples/python/streamlit-multipage-extract-pdf-json/other/client.py", line 127, in delete_specification
    _ = await graphlit.client.delete_specification(st.session_state['specification_id'])
        ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
File "/home/adminuser/venv/lib/python3.11/site-packages/graphlit_api/client.py", line 2034, in delete_specification
    data = self.get_data(response)
           ^^^^^^^^^^^^^^^^^^^^^^^
File "/home/adminuser/venv/lib/python3.11/site-packages/graphlit_api/async_base_client.py", line 141, in get_data
    raise GraphQLClientGraphQLMultiError.from_errors_dicts(
```

**Comment by kirk-marple** [comment] 2024-05-30 21:27
@MPParsley Thanks for letting us know, we'll get that fixed ASAP in the sample app.

**Comment by kirk-marple** [comment] 2024-10-22 00:44
Closing; could not reproduce in current sample app.

**Closed as completed by kirk-marple** 2024-10-22 00:44 UTC
